{"uuid": "a86c25e1-b838-42c2-93bc-b2fa8704e21d", "children": ["33cbad4e-a62d-4819-999d-bcfb2163c1e7"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created\nfrom no such execution context: uniqueContextId not found\n  (Session info: chrome=115.0.5790.171)\nStacktrace:\nBacktrace:\n\tGetHandleVerifier [0x00007FF695294A62+57106]\n\t(No symbol) [0x00007FF69520CF52]\n\t(No symbol) [0x00007FF6950DE2CB]\n\t(No symbol) [0x00007FF6950CC276]\n\t(No symbol) [0x00007FF6950CA5CB]\n\t(No symbol) [0x00007FF6950CAEAE]\n\t(No symbol) [0x00007FF6950E1F17]\n\t(No symbol) [0x00007FF6950E3C5F]\n\t(No symbol) [0x00007FF6950E3D50]\n\t(No symbol) [0x00007FF69513F8EA]\n\t(No symbol) [0x00007FF69513DF60]\n\t(No symbol) [0x00007FF695136793]\n\t(No symbol) [0x00007FF69510CE81]\n\t(No symbol) [0x00007FF69510E064]\n\tGetHandleVerifier [0x00007FF695544222+2873042]\n\tGetHandleVerifier [0x00007FF695596590+3209792]\n\tGetHandleVerifier [0x00007FF69558F3AF+3180639]\n\tGetHandleVerifier [0x00007FF695325F25+652245]\n\t(No symbol) [0x00007FF695218618]\n\t(No symbol) [0x00007FF6952147C4]\n\t(No symbol) [0x00007FF6952148BC]\n\t(No symbol) [0x00007FF695204C33]\n\tBaseThreadInitThunk [0x00007FFE9CE67614+20]\n\tRtlUserThreadStart [0x00007FFE9E7626B1+33]\n\n", "trace": "  File \"C:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pluggy\\_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"D:\\credence\\Orangehrm_pytest_project\\testcases\\conftest.py\", line 16, in setup\n    driver = webdriver.Chrome()\n             ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"C:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 56, in __init__\n    super().__init__(\n  File \"C:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 206, in __init__\n    self.start_session(capabilities)\n  File \"C:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 290, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 345, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1691680952455, "stop": 1691680959300}], "start": 1691680952455, "stop": 1691680959552}