{"uuid": "e0105f4d-d2e3-4d1d-95a5-7ca19219d04a", "children": ["a0a162fc-298a-4614-8888-89159cc3b3a6"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: cannot determine loading status\nfrom no such window\n  (Session info: chrome=115.0.5790.171)\nStacktrace:\nBacktrace:\n\tGetHandleVerifier [0x00007FF695294A62+57106]\n\t(No symbol) [0x00007FF69520CF52]\n\t(No symbol) [0x00007FF6950DE17D]\n\t(No symbol) [0x00007FF6950CC39C]\n\t(No symbol) [0x00007FF6950CA5CB]\n\t(No symbol) [0x00007FF6950CAEAE]\n\t(No symbol) [0x00007FF6950D852A]\n\t(No symbol) [0x00007FF6950E7E61]\n\t(No symbol) [0x00007FF6950EBFFA]\n\t(No symbol) [0x00007FF6950CB477]\n\t(No symbol) [0x00007FF6950E7AF3]\n\t(No symbol) [0x00007FF69514E44F]\n\t(No symbol) [0x00007FF695136793]\n\t(No symbol) [0x00007FF69510CE81]\n\t(No symbol) [0x00007FF69510E064]\n\tGetHandleVerifier [0x00007FF695544222+2873042]\n\tGetHandleVerifier [0x00007FF695596590+3209792]\n\tGetHandleVerifier [0x00007FF69558F3AF+3180639]\n\tGetHandleVerifier [0x00007FF695325F25+652245]\n\t(No symbol) [0x00007FF695218618]\n\t(No symbol) [0x00007FF6952147C4]\n\t(No symbol) [0x00007FF6952148BC]\n\t(No symbol) [0x00007FF695204C33]\n\tBaseThreadInitThunk [0x00007FFE9CE67614+20]\n\tRtlUserThreadStart [0x00007FFE9E7626B1+33]\n\n", "trace": "  File \"C:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pluggy\\_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"D:\\credence\\Orangehrm_pytest_project\\testcases\\conftest.py\", line 32, in setup\n    driver.maximize_window()\n  File \"C:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 497, in maximize_window\n    self.execute(command, None)\n  File \"C:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 345, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1691680106109, "stop": 1691680107949}], "start": 1691680106109, "stop": 1691680108104}